# Generated by Django 3.0.8 on 2020-08-14 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('learner_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(help_text='current job desription', max_length=66)),
                ('linkedin_url', models.URLField(help_text='your linked profile link')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'learner',
            },
        ),
    ]
